name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  EKS_CLUSTER_NAME: healthcare-ms-cluster

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Set environment variables
      run: |
        echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV
        echo "AWS_REGION=${{ env.AWS_REGION }}" >> $GITHUB_ENV

    - name: Apply Kubernetes manifests
      run: |
        # Create namespace if it doesn't exist
        kubectl apply -f kubernetes/namespace.yaml
        
        # Replace variables in manifests
        for file in kubernetes/*.yaml; do
          if [ -f "$file" ]; then
            sed -i "s/\${AWS_ACCOUNT_ID}/$AWS_ACCOUNT_ID/g" "$file"
            sed -i "s/\${AWS_REGION}/$AWS_REGION/g" "$file"
          fi
        done
        
        # Apply manifests
        kubectl apply -f kubernetes/patient-service.yaml
        kubectl apply -f kubernetes/appointment-service.yaml
        kubectl apply -f kubernetes/ingress.yaml
        
        # Verify deployments
        kubectl rollout status deployment/patient-service -n healthcare
        kubectl rollout status deployment/appointment-service -n healthcare
